@startuml
'https://plantuml.com/class-diagram
set namespaceSeparator ::

package "pizza.customer" <<Frame>> {
class CustomerService {
+ getCustomerByPhoneNumber(phone:String) : Customer
+ getAllCustomers() : Iterable<Customer>
+ createCustomer(c:Customer) : Customer
}
}

CustomerService -right-> ArrayList
@enduml