@startuml
'https://plantuml.com/class-diagram
set namespaceSeparator ::

package "pizza.order" <<Frame>> {
class OrderService
}

package "pizza.product" <<Frame>> {
class ProductService
}

package "pizza.customer" <<Frame>> {
class CustomerService
}

OrderService -right-> ArrayList
OrderService -down-> ProductService
OrderService -down-> CustomerService
@enduml