@startuml
'https://plantuml.com/class-diagram
set namespaceSeparator ::

package "pizza.product" <<Frame>> {
class ProductService {
createProduct(p : Product)
getProduct(id : String) : Product
getAllProducts() : Iterable<Product>
getTotalPrice(prdQnts : Map<String,Integer>) : double
}
interface ProductRepository
class ProductJdbcDao implements ProductRepository
}

interface DataSource

ProductService -right-> ProductRepository
ProductJdbcDao .-right-> DataSource
@enduml