@startuml
'https://plantuml.com/class-diagram
set namespaceSeparator ::

package "javax.sql" <<Frame>> {
    interface DataSource {
        getConnection() : Connection
    }
}

package "pizza.product" <<Frame>> {

    class ProductService {
        createProduct(p : Product)
        getProduct(id : String) : Product
        getAllProducts() : Iterable<Product>
        getTotalPrice(prdQnts : Map<String,Integer>) : double
    }

    interface ProductRepository {
        save(p : Product) : Product
        existsById(id : String) : bool
        findAll() : Collection<Product>
        findById(id : String) : Optional<Product>
    }

    class JdbcProductRepository implements ProductRepository {
    }
    class InMemoryProductRepository implements ProductRepository {
    }

    ProductService -right-> ProductRepository
    InMemoryProductRepository -[hidden]> JdbcProductRepository
    JdbcProductRepository .-right-> DataSource
}

@enduml