@startuml
'https://plantuml.com/class-diagram
set namespaceSeparator ::

package "pizza.product" <<Frame>> {
class ProductService
interface ProductRepository
class ProductJdbcDao extends ProductRepository
}

ProductService -right-> ProductRepository
ProductJdbcDao -right-> DataSource
@enduml